# Generated by Django 4.1.2 on 2022-10-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='power',
            field=models.IntegerField(default=0, verbose_name='poder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='power',
            field=models.IntegerField(default=0, verbose_name='poder'),
            preserve_default=False,
        ),
    ]
