version: '3'
services:
  db:
    image: 'postgres:13.7-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ".:/app:rw"
